#!/bin/bash

# Completion stuff
source ~/.bash_completion.d/complete_alias

# Linux settings
alias lsettings="code ~/Linux-settings"

# Directories
alias sk="cd ~/Desktop"
alias keys="cd /usr/share/X11/xkb/symbols"

# Applications
alias nt="nautilus ."
alias op="xdg-open"
complete -F _complete_alias op

# Vim
alias as="vim ~/Linux-settings/skriftur/bash/aliases"
alias bs="vim ~/Linux-settings/bashrc"
alias tm="vim temp"

# TeX
alias ltx="code ~/Documents/tex"
alias tx="pdflatex"
complete -F _complete_alias tx

# Minecraft server
alias mserver="cd ~/minecraft_server && java -Xmx1024M -Xms1024M -jar server.jar nogui"

# Misc
alias c="xclip -selection clipboard"
alias v="xclip -o -selection clipboard"
alias cl="clear"

# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls'

# Build
alias sv="~/Linux-settings/build.sh"
alias ssv="~/Linux-settings/sbuild.sh"

# Python venv
alias snek="source ~/.virtualenvs/snek/bin/activate"
alias fishing7="source ~/.virtualenvs/fishingderby/bin/activate"
alias fishing6="source ~/.virtualenvs/fishingderby3.6/bin/activate"
alias kthqa="source ~/.virtualenvs/kthqa/bin/activate"
alias osmpy="source ~/.virtualenvs/osmpy/bin/activate"
